### ISSUE TITLE
Sorting model id

### ISSUE THREAD

**Issue by grodriguez85** [ibarrick/paper-data-table#14]
The model ID is sorted as a string and not like a number, even with numeric=true. So numbers like 10 are sorted before 19 on ascending. Any way to solve this? 

Thanks.

**Comment by n1ru4l** [comment]
The model is is a string. You could add a computed property which parses the numeric values of the model and use that property for sorting.

**Comment by grodriguez85** [comment]
Excellent idea, thanks!

My computed property on the model is like this:

`numericId: Ember.computed('id',function(){
      return parseInt(this.get('id'));
}),`
