### ISSUE TITLE
Add Travis integration?

### ISSUE THREAD

**Issue by panthony** [ibarrick/paper-data-table#18]
Would you consider adding Travis integration ?

I'm aware of the lack of tests for now but maybe that will change in the future 😄

**Comment by ibarrick** [comment]
I'll look into it now since we actually have some tests (thanks to you)!

**Comment by panthony** [comment]
Thanks !

I did it for ember-paper-tabs by copying https://github.com/miguelcobain/ember-paper-expansion-panel.

This is pretty straight forward :)

**Comment by ibarrick** [comment]
I think that it's done. I submitted a test PR to move the travis CI badge and it looks like we're all set. The badge still says build unknown for some reason but maybe it just needs some time.
