### ISSUE TITLE
Table row height is missing

### ISSUE THREAD

**Issue by olgabrani** [ibarrick/paper-data-table#22]
Table rows seem to be missing their height property.
This is how it is supposed to look:
<img width="818" alt="correct" src="https://cloud.githubusercontent.com/assets/2444615/25748292/40ce2d82-31b3-11e7-96d3-9e0a969797ad.png">
and this is how it actually looks:
<img width="826" alt="wrong" src="https://cloud.githubusercontent.com/assets/2444615/25748313/4faf540c-31b3-11e7-8d3a-058540c97ec7.png">

As far as I can tell, this is introduced by this commit: https://github.com/ibarrick/paper-data-table/commit/46a6979a1bdcdb65cb200c94993bca75ac25c213 @n1ru4l

It seems that `tbody` element is missing `md-body` class and thus causing the rows to loose their height as the rule
```
table.md-table tbody.md-body > tr.md-row,
  table.md-table tfoot.md-foot > tr.md-row {
    height: 48px; }
```
does not apply.

A solution would be to replace `classNameBindings` with `classNames` in
https://github.com/ibarrick/paper-data-table/commit/46a6979a1bdcdb65cb200c94993bca75ac25c213#diff-9e23e22275d0278af7ed7e546b5a3fe9R10

```
 export default Component.extend({
-       classNameBindings: ['md-body'],
+       classNames: ['md-body'],
        attributeBindings: ['style'],
        layout,
        tagName: 'tbody',
```

**Comment by n1ru4l** [comment]
Damn :/ Would you like to do a PR otherwise I will do one in about 2 hours

**Comment by olgabrani** [comment]
I opened https://github.com/ibarrick/paper-data-table/pull/23
