### ISSUE TITLE
Outdated dependencies and tests not running

### ISSUE THREAD

**Issue by Subtletree** [ibarrick/paper-data-table#42]
Hi @ibarrick I notice that you haven't been active with `paper-data-table` for a while.

If I put forward a PR updating all dependencies and getting the test suite running again would you be able to merge it?

Just wanted to make sure you're around and able to merge it before doing the work 🙂

**Comment by ibarrick** [comment]
Yeah I can do that. I've been really swamped with a start-up, I will try to be more active though.

**Comment by Subtletree** [comment]
Sweet! Oh absolutely understand, not intending to hit you up at all. Let you know when I get on to it
